# Generated by Django 5.2 on 2025-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
