# Generated by Django 5.2 on 2025-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_lab', '0003_alter_pizza_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='end_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Приготовлено пицц'),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='is_ready',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен?'),
        ),
    ]
